name: Deploy to hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Copiar a servidor FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ ftp.HOST }}
          username: ${{ ftp.USER }}
          password: ${{ ftp.PASS }}
          local-dir: ./public_html/
          remote-dir: /
